version: "3.7"

services:
  server-dummy:
    container_name: ${DOCKER_REPOSITORY_USERNAME}-${DOCKER_REPOSITORY_NAME}-dev
    image: ${DOCKER_REPOSITORY_USERNAME}/${DOCKER_REPOSITORY_NAME}-dev:latest
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev_
    # command: tail -f /dev/null
    entrypoint: docker-entrypoint.sh
    command: app
    init: true
    ports:
        # container
      - target: 3000
        # host
        published: 3000
        protocol: tcp
        mode: host
    networks:
      - shared
    volumes:
      - type: bind
        source: ./data
        target: /data
      - type: bind
        source: ./src
        target: /app/src
    env_file:
      - ./.env
    healthcheck:
      # test: ["CMD", "docker-healthcheck"]
      test: ["CMD", "curl", "--fail", "http://localhost:3000/check"]
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 1m
    stop_grace_period: 30s
    restart: always

# volumes:
#   data:
#     name: ${DOCKER_REPOSITORY_USERNAME}-${DOCKER_REPOSITORY_NAME}-data

networks:
  shared:
    name: ${DOCKER_NETWORK}
